# -*- coding: utf-8 -*-
"""DCFScript.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TC9N_qDcaD82LCGPLIcKrb1Gi8LA0VuP
"""

import os
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

#Company
tckr = yf.Ticker(input("Please input a ticker: "))

#Financial Data
income_stmt = tckr.financials
balance_sheet = tckr.balance_sheet
cash_flow = tckr.cashflow
info = tckr.info

#Cashflow Calculation
    # = EBIT × (1 - tax rate) + D&A − CapEx − change in working capital
tax_rate = income_stmt.loc['Tax Provision'].iloc[0] / income_stmt.loc['Pretax Income'].iloc[0]
ebit = income_stmt.loc['EBIT'].iloc[0]
da = cash_flow.loc['Depreciation And Amortization'].iloc[0]
capex = cash_flow.loc['Capital Expenditure'].iloc[0]
historical_fcf = ebit * (1-tax_rate) + da - capex
historical_fcf_4yr = (
    income_stmt.loc['EBIT'].iloc[0:4] * (1 - tax_rate) +
    cash_flow.loc['Depreciation And Amortization'].iloc[0:4] -
    cash_flow.loc['Capital Expenditure'].iloc[0:4]
)

#Projected Cashflow
revenue_growth = float(input("What is projected revenue growth? (decimal)"))
sd_revenue_growth = np.std(income_stmt.loc['Total Revenue'].iloc[0:4].pct_change())
fcf_margin = historical_fcf / info['totalRevenue']
sd_fcf_margin = np.std(historical_fcf_4yr / income_stmt.loc['Total Revenue'].iloc[0:4])
last_revenue = income_stmt.loc['Total Revenue'].iloc[0]
if last_revenue >= 1_000_000_000:
    SCALE = 1_000_000
    SCALE_LABEL = "$ in millions"
else:
    SCALE = 1_000
    SCALE_LABEL = "$ in thousands"
#Regular
projected_revenue = last_revenue * (1 + revenue_growth) ** np.arange(1,6)
projected_fcf = projected_revenue * fcf_margin
bear = {
    'growth': revenue_growth - sd_revenue_growth,
    'fcf_margin': fcf_margin - sd_fcf_margin,
    'terminal_growth': 0.015
}
bull = {
    'growth': revenue_growth + sd_revenue_growth,
    'fcf_margin': fcf_margin + sd_fcf_margin,
    'terminal_growth': 0.025
}
#Bear
bear_projected_revenue = last_revenue * (1 + bear['growth']) ** np.arange(1,6)
bear_projected_fcf = bear_projected_revenue * bear['fcf_margin']
#Bull
bull_projected_revenue = last_revenue * (1 + bull['growth']) ** np.arange(1,6)
bull_projected_fcf = bull_projected_revenue * bull['fcf_margin']

#WACC
risk_free = float(input("Please enter current risk-free rate: (10-yr Treasury)"))
market_premium = 0.057
beta = info['beta']
wacc = risk_free + beta * market_premium

#Terminal Value
    # TV = FCF_last × (1 + 0.02) / (WACC − g)
terminal_growth = 0.02
terminal_value = projected_fcf[-1] * (1 + terminal_growth) / (wacc - terminal_growth)
bull_terminal_value = bull_projected_fcf[-1] * (1 + bull['terminal_growth']) / (wacc - bull['terminal_growth'])
bear_terminal_value = bear_projected_fcf[-1] * (1 + bear['terminal_growth']) / (wacc - bear['terminal_growth'])

#Discount
discount_factors = (1 + wacc) ** np.arange(1,6)
pv_fcfs = np.sum(projected_fcf / discount_factors)
bull_pv_fcfs = np.sum(bull_projected_fcf / discount_factors)
bear_pv_fcfs = np.sum(bear_projected_fcf / discount_factors)
pv_terminal = terminal_value / discount_factors[-1]
bull_pv_terminal = bull_terminal_value / discount_factors[-1]
bear_pv_terminal = bear_terminal_value / discount_factors[-1]
enterprise_value = pv_fcfs + pv_terminal
bull_enterprise_value = bull_pv_fcfs + bull_pv_terminal
bear_enterprise_value = bear_pv_fcfs + bear_pv_terminal

#Equity value
net_debt = info['totalDebt'] - info['totalCash']
equity_value = enterprise_value - net_debt
bull_equity_value = bull_enterprise_value - net_debt
bear_equity_value = bear_enterprise_value - net_debt
price_per_share = equity_value / info['sharesOutstanding']
bull_price_per_share = bull_equity_value / info['sharesOutstanding']
bear_price_per_share = bear_equity_value / info['sharesOutstanding']

print(f"(All valuations in {SCALE_LABEL})")
print(f"Fair price per share: ${int(price_per_share)}")
print(f"Fair valuation: ${int(price_per_share * info['sharesOutstanding'] / SCALE):,}")
print(f"Bull price per share: ${int(bull_price_per_share)}")
print(f"Bull valuation: ${int(bull_price_per_share * info['sharesOutstanding'] / SCALE):,}")
print(f"Bear price per share: ${int(bear_price_per_share)}")
print(f"Bear valuation: ${int(bear_price_per_share * info['sharesOutstanding'] / SCALE):,}")

#Visual model
ticker_name = info.get('shortName', tckr.ticker)
current_price = info.get('currentPrice', info.get('regularMarketPrice', None))
fig, axes = plt.subplots(1, 2, figsize=(12, 6))
fig.suptitle(f'{ticker_name} — DCF Analysis', fontsize=15, fontweight='bold', y=1.01)

#DCF price vs market
ax1 = axes[0]
labels = ['Bearish DCF', 'DCF Fair Value', 'Bullish DCF']
values_prices = [bear_price_per_share, price_per_share, bull_price_per_share]
colors = ['red', 'steelblue', 'green']
ax1.axhline(current_price, color='black', linewidth=1, linestyle='--', label=f'Market ${current_price:.0f}')
ax1.legend(fontsize=9)
bars = ax1.bar(labels, values_prices, color=colors, edgecolor='white', linewidth=0.5, width=0.4)
for bar, val in zip(bars, values_prices):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
             f'${val:.0f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
if current_price:
    margin = ((price_per_share - current_price) / current_price) * 100
    sign = '+' if margin > 0 else ''
    ax1.set_title(f'Fair Value vs Market  ({sign}{margin:.1f}%)', fontsize=12)
else:
    ax1.set_title('DCF Fair Value', fontsize=12)
ax1.set_ylabel('Price per Share ($)')
ax1.yaxis.set_major_formatter(mticker.FormatStrFormatter('$%.0f'))
ax1.spines[['top', 'right']].set_visible(False)

#WACC sensitivity heatmap
ax2 = axes[1]
wacc_range = np.linspace(wacc - 0.02, wacc + 0.02, 5)
tg_range = np.linspace(0.01, 0.03, 5)
sensitivity = np.zeros((5, 5))
for i, tg in enumerate(tg_range):
    for j, w in enumerate(wacc_range):
        if w <= tg:
            sensitivity[i, j] = np.nan
            continue
        tv = projected_fcf[-1] * (1 + tg) / (w - tg)
        df = (1 + w) ** np.arange(1, 6)
        ev = np.sum(projected_fcf / df) + tv / df[-1]
        sensitivity[i, j] = (ev - net_debt) / info['sharesOutstanding']

im = ax2.imshow(sensitivity, cmap='RdYlGn', aspect='auto')
ax2.set_xticks(range(5))
ax2.set_yticks(range(5))
ax2.set_xticklabels([f'{w*100:.1f}%' for w in wacc_range], fontsize=8)
ax2.set_yticklabels([f'{tg*100:.1f}%' for tg in tg_range], fontsize=8)
ax2.set_xlabel('WACC')
ax2.set_ylabel('Terminal growth rate')
ax2.set_title('Price sensitivity ($)', fontsize=12)
for i in range(5):
    for j in range(5):
        val = sensitivity[i, j]
        if not np.isnan(val):
            ax2.text(j, i, f'${val:.0f}', ha='center', va='center',
                     fontsize=8, color='black', fontweight='bold')
plt.colorbar(im, ax=ax2, format='$%.0f')
plt.tight_layout()
plt.savefig(os.path.join(os.path.expanduser("~"), "Downloads", f'{ticker_name}_dcf.png'), dpi=150, bbox_inches='tight')
plt.show()
print(f"Chart saved as {ticker_name}_dcf.png")

#Excel export
export_state = input("Would you like to export to Excel? (yes/no): ").strip().lower()
if export_state == 'yes':
    from openpyxl import Workbook
    from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
    from openpyxl.drawing.image import Image as XLImage
    import datetime, os

    def _fill(hex_color):
        return PatternFill("solid", fgColor=hex_color)

    def _font(bold=False, size=11, color="000000", italic=False):
        return Font(name='Calibri', bold=bold, size=size, color=color, italic=italic)

    _thin   = Side(style='thin', color="D9D9D9")
    _border = Border(left=_thin, right=_thin, top=_thin, bottom=_thin)
    _center = Alignment(horizontal='center', vertical='center', wrap_text=True)
    _left   = Alignment(horizontal='left',   vertical='center', indent=1)

    NAVY    = _fill("1F3864")
    ACCENT  = _fill("2E75B6")
    BEAR_BG = _fill("FFD7D7")
    BASE_BG = _fill("DDEEFF")
    BULL_BG = _fill("D6F5DA")
    GRAY_BG = _fill("F2F2F2")
    WHITE   = _fill("FFFFFF")

    SHARE_FMT = '$#,##0.00'
    MONEY_FMT = '$#,##0'
    PCT_FMT   = '0.00%'
    NUM_FMT   = '#,##0'
    M = SCALE

    wb = Workbook()

    # ── Sheet 1: DCF Summary ────────────────────────────────────────────────────
    ws1 = wb.active
    ws1.title = "DCF Summary"
    ws1.sheet_view.showGridLines = False
    for i, w in enumerate([30, 18, 18, 18], 1):
        ws1.column_dimensions[get_column_letter(i)].width = w

    ws1.merge_cells('A1:D1')
    ws1['A1'].value = f"  {ticker_name}  —  Discounted Cash Flow Model"
    ws1['A1'].font = _font(bold=True, size=16, color="FFFFFF")
    ws1['A1'].fill = NAVY
    ws1['A1'].alignment = _left
    ws1.row_dimensions[1].height = 36

    ws1.merge_cells('A2:D2')
    price_str = f"${current_price:.2f}" if current_price else "N/A"
    ws1['A2'].value = f"  {tckr.ticker.upper()}  |  Market Price: {price_str}  |  {datetime.date.today().strftime('%B %d, %Y')}"
    ws1['A2'].font = _font(italic=True, size=10, color="FFFFFF")
    ws1['A2'].fill = ACCENT
    ws1['A2'].alignment = _left
    ws1.row_dimensions[2].height = 20

    r = 4

    # Key Assumptions section
    ws1.merge_cells(f'A{r}:D{r}')
    ws1[f'A{r}'].value = "KEY ASSUMPTIONS"
    ws1[f'A{r}'].font = _font(bold=True, size=11, color="FFFFFF")
    ws1[f'A{r}'].fill = ACCENT
    ws1[f'A{r}'].alignment = _center
    ws1.row_dimensions[r].height = 22
    r += 1

    for col, label in enumerate(['Assumption', 'Bear', 'Base', 'Bull'], 1):
        c = ws1.cell(row=r, column=col, value=label)
        c.font = _font(bold=True, size=10, color="FFFFFF"); c.fill = NAVY; c.alignment = _center; c.border = _border
    r += 1

    for i, (label, bv, mv, uv, fmt) in enumerate([
        ("Revenue Growth",  bear['growth'],          revenue_growth,  bull['growth'],          PCT_FMT),
        ("FCF Margin",      bear['fcf_margin'],      fcf_margin,      bull['fcf_margin'],      PCT_FMT),
        ("Terminal Growth", bear['terminal_growth'], terminal_growth, bull['terminal_growth'], PCT_FMT),
        ("WACC",            wacc, wacc, wacc, PCT_FMT),
        ("Beta",            beta, beta, beta, '0.00'),
        ("Risk-Free Rate",  risk_free, risk_free, risk_free, PCT_FMT),
        ("Tax Rate",        tax_rate, tax_rate, tax_rate, PCT_FMT),
    ]):
        bg = GRAY_BG if i % 2 == 0 else WHITE
        c = ws1.cell(row=r, column=1, value=label)
        c.font = _font(bold=True, size=10); c.fill = bg; c.alignment = _left; c.border = _border
        for col, val, sbg in [(2, bv, BEAR_BG), (3, mv, BASE_BG), (4, uv, BULL_BG)]:
            c = ws1.cell(row=r, column=col, value=val)
            c.number_format = fmt; c.font = _font(size=10); c.fill = sbg; c.alignment = _center; c.border = _border
        r += 1

    r += 1

    # Valuation Summary section
    ws1.merge_cells(f'A{r}:D{r}')
    ws1[f'A{r}'].value = f"VALUATION SUMMARY  ({SCALE_LABEL}, except per share data)"
    ws1[f'A{r}'].font = _font(bold=True, size=11, color="FFFFFF")
    ws1[f'A{r}'].fill = ACCENT
    ws1[f'A{r}'].alignment = _center
    ws1.row_dimensions[r].height = 22
    r += 1

    for col, label in enumerate(['Metric', 'Bear', 'Base', 'Bull'], 1):
        c = ws1.cell(row=r, column=col, value=label)
        c.font = _font(bold=True, size=10, color="FFFFFF"); c.fill = NAVY; c.alignment = _center; c.border = _border
    r += 1

    mos_base = ((price_per_share - current_price) / current_price) if current_price else None
    mos_bull  = ((bull_price_per_share - current_price) / current_price) if current_price else None
    mos_bear  = ((bear_price_per_share - current_price) / current_price) if current_price else None

    for i, (label, bv, mv, uv, fmt, hl) in enumerate([
        ("PV of FCFs",           bear_pv_fcfs/M,          pv_fcfs/M,          bull_pv_fcfs/M,          MONEY_FMT, False),
        ("PV of Terminal Value", bear_pv_terminal/M,      pv_terminal/M,      bull_pv_terminal/M,      MONEY_FMT, False),
        ("Enterprise Value",     bear_enterprise_value/M, enterprise_value/M, bull_enterprise_value/M, MONEY_FMT, False),
        ("(−) Net Debt",         net_debt/M,              net_debt/M,         net_debt/M,              MONEY_FMT, False),
        ("Equity Value",         bear_equity_value/M,     equity_value/M,     bull_equity_value/M,     MONEY_FMT, False),
        ("Shares Outstanding",   info['sharesOutstanding'], info['sharesOutstanding'], info['sharesOutstanding'], NUM_FMT, False),
        ("Price Per Share",      bear_price_per_share,  price_per_share,  bull_price_per_share,  SHARE_FMT, True),
        ("Current Market Price", current_price,         current_price,    current_price,         SHARE_FMT, False),
        ("Margin of Safety",     mos_bear,              mos_base,         mos_bull,              PCT_FMT,   True),
    ]):
        bg = GRAY_BG if i % 2 == 0 else WHITE
        c = ws1.cell(row=r, column=1, value=label)
        c.font = _font(bold=hl, size=11 if hl else 10); c.fill = bg; c.alignment = _left; c.border = _border
        for col, val, sbg in [(2, bv, BEAR_BG), (3, mv, BASE_BG), (4, uv, BULL_BG)]:
            c = ws1.cell(row=r, column=col, value=val)
            c.number_format = fmt; c.font = _font(bold=hl, size=11 if hl else 10)
            c.fill = sbg if hl else bg; c.alignment = _center; c.border = _border
        r += 1

    # ── Sheet 2: Projected Financials ──────────────────────────────────────────
    ws2 = wb.create_sheet("Projected Financials")
    ws2.sheet_view.showGridLines = False
    ws2.column_dimensions['A'].width = 22
    for i in range(2, 8):
        ws2.column_dimensions[get_column_letter(i)].width = 16

    ws2.merge_cells('A1:G1')
    ws2['A1'].value = f"  {ticker_name}  —  Projected Financials (5-Year)"
    ws2['A1'].font = _font(bold=True, size=14, color="FFFFFF")
    ws2['A1'].fill = NAVY; ws2['A1'].alignment = _left
    ws2.row_dimensions[1].height = 30

    r2 = 3
    for section_title, rows_data in [
        (f"PROJECTED REVENUE  ({SCALE_LABEL})", [
            ("Bear", bear_projected_revenue, BEAR_BG),
            ("Base", projected_revenue,      BASE_BG),
            ("Bull", bull_projected_revenue, BULL_BG),
        ]),
        (f"PROJECTED FREE CASH FLOW  ({SCALE_LABEL})", [
            ("Bear", bear_projected_fcf, BEAR_BG),
            ("Base", projected_fcf,      BASE_BG),
            ("Bull", bull_projected_fcf, BULL_BG),
        ]),
    ]:
        ws2.merge_cells(f'A{r2}:G{r2}')
        ws2[f'A{r2}'].value = section_title
        ws2[f'A{r2}'].font = _font(bold=True, size=11, color="FFFFFF")
        ws2[f'A{r2}'].fill = ACCENT; ws2[f'A{r2}'].alignment = _center
        ws2.row_dimensions[r2].height = 22
        r2 += 1

        c = ws2.cell(row=r2, column=1, value="Scenario")
        c.font = _font(bold=True, size=10, color="FFFFFF"); c.fill = NAVY; c.alignment = _center; c.border = _border
        for col, yr in enumerate(range(1, 6), 2):
            c = ws2.cell(row=r2, column=col, value=f"Year {yr}")
            c.font = _font(bold=True, size=10, color="FFFFFF"); c.fill = NAVY; c.alignment = _center; c.border = _border
        r2 += 1

        for label, values, sbg in rows_data:
            c = ws2.cell(row=r2, column=1, value=label)
            c.font = _font(bold=True, size=10); c.fill = sbg; c.alignment = _left; c.border = _border
            for col, val in enumerate(values, 2):
                c = ws2.cell(row=r2, column=col, value=float(val) / M)
                c.number_format = MONEY_FMT; c.font = _font(size=10); c.fill = sbg; c.alignment = _center; c.border = _border
            r2 += 1
        r2 += 1

    # ── Sheet 3: WACC Sensitivity ──────────────────────────────────────────────
    ws3 = wb.create_sheet("WACC Sensitivity")
    ws3.sheet_view.showGridLines = False
    ws3.column_dimensions['A'].width = 16
    for i in range(2, 8):
        ws3.column_dimensions[get_column_letter(i)].width = 14

    ws3.merge_cells('A1:G1')
    ws3['A1'].value = f"  {ticker_name}  —  Price Sensitivity  (WACC × Terminal Growth Rate)"
    ws3['A1'].font = _font(bold=True, size=14, color="FFFFFF")
    ws3['A1'].fill = NAVY; ws3['A1'].alignment = _left
    ws3.row_dimensions[1].height = 30

    ws3.merge_cells('A2:G2')
    ws3['A2'].value = (
        f"  Price Per Share ($)  |  Base WACC: {wacc*100:.2f}%  |  "
        f"Terminal Growth: {terminal_growth*100:.1f}%  |  Market: {price_str}"
    )
    ws3['A2'].font = _font(italic=True, size=10, color="595959")
    ws3['A2'].fill = _fill("F5F5F5"); ws3['A2'].alignment = _left

    r3 = 4
    c = ws3.cell(row=r3, column=1, value="WACC \\ Term. Gr.")
    c.font = _font(bold=True, size=9, color="FFFFFF"); c.fill = NAVY; c.alignment = _center; c.border = _border
    ws3.row_dimensions[r3].height = 28
    for col_idx, tg in enumerate(tg_range, 2):
        c = ws3.cell(row=r3, column=col_idx, value=tg)
        c.number_format = PCT_FMT; c.font = _font(bold=True, size=10, color="FFFFFF")
        c.fill = ACCENT; c.alignment = _center; c.border = _border
    r3 += 1

    min_val = float(np.nanmin(sensitivity))
    max_val = float(np.nanmax(sensitivity))

    for j, w in enumerate(wacc_range):
        c = ws3.cell(row=r3, column=1, value=w)
        c.number_format = PCT_FMT; c.font = _font(bold=True, size=10, color="FFFFFF")
        c.fill = ACCENT; c.alignment = _center; c.border = _border
        for col_idx, _ in enumerate(tg_range, 2):
            i_tg = col_idx - 2
            val = sensitivity[i_tg, j]
            c = ws3.cell(row=r3, column=col_idx)
            if np.isnan(val):
                c.value = "N/A"; c.fill = _fill("D9D9D9"); c.font = _font(size=10, color="999999")
            else:
                c.value = float(val)
                c.number_format = SHARE_FMT
                ratio = (val - min_val) / (max_val - min_val) if max_val != min_val else 0.5
                if ratio < 0.5:
                    r_ch = 255; g_ch = int(510 * ratio); b_ch = 0
                else:
                    r_ch = int(510 * (1 - ratio)); g_ch = 255; b_ch = 0
                r_ch = min(255, max(0, r_ch)); g_ch = min(255, max(0, g_ch))
                c.fill = _fill(f"{r_ch:02X}{g_ch:02X}{b_ch:02X}")
                c.font = _font(bold=True, size=10)
            c.alignment = _center; c.border = _border
        r3 += 1

    # ── Sheet 4: Chart ──────────────────────────────────────────────────────────
    chart_path = os.path.join(os.path.expanduser("~"), "Downloads", f'{ticker_name}_dcf.png')
    if os.path.exists(chart_path):
        ws4 = wb.create_sheet("Chart")
        ws4.sheet_view.showGridLines = False
        ws4.merge_cells('A1:P1')
        ws4['A1'].value = f"  {ticker_name}  —  DCF Analysis Chart"
        ws4['A1'].font = _font(bold=True, size=14, color="FFFFFF")
        ws4['A1'].fill = NAVY; ws4['A1'].alignment = _left
        ws4.row_dimensions[1].height = 30
        img = XLImage(chart_path)
        img.anchor = 'A3'
        ws4.add_image(img)

    out_file = os.path.join(os.path.expanduser("~"), "Downloads", f'{tckr.ticker.upper()}_dcf_results.xlsx')
    wb.save(out_file)
    print(f"Excel report saved as {out_file}")
