# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TC9N_qDcaD82LCGPLIcKrb1Gi8LA0VuP
"""

!pip install yfinance pandas numpy matplotlib
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

#Company
tckr = yf.Ticker(input("Please input a ticker: "))

#Financial Data
income_stmt = tckr.financials
balance_sheet = tckr.balance_sheet
cash_flow = tckr.cashflow
info = tckr.info

#Cashflow Calculation
    # = EBIT × (1 - tax rate) + D&A − CapEx − change in working capital
tax_rate = income_stmt.loc['Tax Provision'].iloc[0] / income_stmt.loc['Pretax Income'].iloc[0]
ebit = income_stmt.loc['EBIT'].iloc[0]
da = cash_flow.loc['Depreciation And Amortization'].iloc[0]
capex = cash_flow.loc['Capital Expenditure'].iloc[0]
historical_fcf = ebit * (1-tax_rate) + da - capex
historical_fcf_4yr = (
    income_stmt.loc['EBIT'].iloc[0:4] * (1 - tax_rate) +
    cash_flow.loc['Depreciation And Amortization'].iloc[0:4] -
    cash_flow.loc['Capital Expenditure'].iloc[0:4]
)

#Projected Cashflow
revenue_growth = float(input("What is projected revenue growth? (decimal)"))
sd_revenue_growth = np.std(income_stmt.loc['Total Revenue'].iloc[0:4].pct_change())
fcf_margin = historical_fcf / info['totalRevenue']
sd_fcf_margin = np.std(historical_fcf_4yr / income_stmt.loc['Total Revenue'].iloc[0:4])
last_revenue = income_stmt.loc['Total Revenue'].iloc[0]
#Regular
projected_revenue = last_revenue * (1 + revenue_growth) ** np.arange(1,6)
projected_fcf = projected_revenue * fcf_margin
bear = {
    'growth': revenue_growth - sd_revenue_growth,
    'fcf_margin': fcf_margin - sd_fcf_margin,
    'terminal_growth': 0.015
}
bull = {
    'growth': revenue_growth + sd_revenue_growth,
    'fcf_margin': fcf_margin + sd_fcf_margin,
    'terminal_growth': 0.025
}
#Bear
bear_projected_revenue = last_revenue * (1 + bear['growth']) ** np.arange(1,6)
bear_projected_fcf = bear_projected_revenue * bear['fcf_margin']
#Bull
bull_projected_revenue = last_revenue * (1 + bull['growth']) ** np.arange(1,6)
bull_projected_fcf = bull_projected_revenue * bull['fcf_margin']

#WACC
risk_free = float(input("Please enter current risk-free rate: (10-yr Treasury)"))
market_premium = 0.057
beta = info['beta']
wacc = risk_free + beta * market_premium

#Terminal Value
    # TV = FCF_last × (1 + 0.02) / (WACC − g)
terminal_growth = 0.02
terminal_value = projected_fcf[-1] * (1 + terminal_growth) / (wacc - terminal_growth)
bull_terminal_value = bull_projected_fcf[-1] * (1 + bull['terminal_growth']) / (wacc - bull['terminal_growth'])
bear_terminal_value = bear_projected_fcf[-1] * (1 + bear['terminal_growth']) / (wacc - bear['terminal_growth'])

#Discount
discount_factors = (1 + wacc) ** np.arange(1,6)
pv_fcfs = np.sum(projected_fcf / discount_factors)
bull_pv_fcfs = np.sum(bull_projected_fcf / discount_factors)
bear_pv_fcfs = np.sum(bear_projected_fcf / discount_factors)
pv_terminal = terminal_value / discount_factors[-1]
bull_pv_terminal = bull_terminal_value / discount_factors[-1]
bear_pv_terminal = bear_terminal_value / discount_factors[-1]
enterprise_value = pv_fcfs + pv_terminal
bull_enterprise_value = bull_pv_fcfs + bull_pv_terminal
bear_enterprise_value = bear_pv_fcfs + bear_pv_terminal

#Equity value
net_debt = info['totalDebt'] - info['totalCash']
equity_value = enterprise_value - net_debt
bull_equity_value = bull_enterprise_value - net_debt
bear_equity_value = bear_enterprise_value - net_debt
price_per_share = equity_value / info['sharesOutstanding']
bull_price_per_share = bull_equity_value / info['sharesOutstanding']
bear_price_per_share = bear_equity_value / info['sharesOutstanding']

print(f"Fair price per share: ${int(price_per_share)}")
print(f"Fair valuation: ${int(price_per_share * info['sharesOutstanding'])}")
print(f"Bull price per share: ${int(bull_price_per_share)}")
print(f"Bull valuation: ${int(bull_price_per_share * info['sharesOutstanding'])}")
print(f"Bear price per share: ${int(bear_price_per_share)}")
print(f"Bear valuation: ${int(bear_price_per_share * info['sharesOutstanding'])}")

#Visual model
ticker_name = info.get('shortName', tckr.ticker)
current_price = info.get('currentPrice', info.get('regularMarketPrice', None))
fig, axes = plt.subplots(1, 2, figsize=(12, 6))
fig.suptitle(f'{ticker_name} — DCF Analysis', fontsize=15, fontweight='bold', y=1.01)

#DCF price vs market
ax1 = axes[0]
labels = ['Bearish DCF', 'DCF Fair Value', 'Bullish DCF']
values_prices = [bear_price_per_share, price_per_share, bull_price_per_share]
colors = ['red', 'steelblue', 'green']
ax1.axhline(current_price, color='black', linewidth=1, linestyle='--', label=f'Market ${current_price:.0f}')
ax1.legend(fontsize=9)
bars = ax1.bar(labels, values_prices, color=colors, edgecolor='white', linewidth=0.5, width=0.4)
for bar, val in zip(bars, values_prices):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
             f'${val:.0f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
if current_price:
    margin = ((price_per_share - current_price) / current_price) * 100
    sign = '+' if margin > 0 else ''
    ax1.set_title(f'Fair Value vs Market  ({sign}{margin:.1f}%)', fontsize=12)
else:
    ax1.set_title('DCF Fair Value', fontsize=12)
ax1.set_ylabel('Price per Share ($)')
ax1.yaxis.set_major_formatter(mticker.FormatStrFormatter('$%.0f'))
ax1.spines[['top', 'right']].set_visible(False)

#WACC sensitivity heatmap
ax2 = axes[1]
wacc_range = np.linspace(wacc - 0.02, wacc + 0.02, 5)
tg_range = np.linspace(0.01, 0.03, 5)
sensitivity = np.zeros((5, 5))
for i, tg in enumerate(tg_range):
    for j, w in enumerate(wacc_range):
        if w <= tg:
            sensitivity[i, j] = np.nan
            continue
        tv = projected_fcf[-1] * (1 + tg) / (w - tg)
        df = (1 + w) ** np.arange(1, 6)
        ev = np.sum(projected_fcf / df) + tv / df[-1]
        sensitivity[i, j] = (ev - net_debt) / info['sharesOutstanding']

im = ax2.imshow(sensitivity, cmap='RdYlGn', aspect='auto')
ax2.set_xticks(range(5))
ax2.set_yticks(range(5))
ax2.set_xticklabels([f'{w*100:.1f}%' for w in wacc_range], fontsize=8)
ax2.set_yticklabels([f'{tg*100:.1f}%' for tg in tg_range], fontsize=8)
ax2.set_xlabel('WACC')
ax2.set_ylabel('Terminal growth rate')
ax2.set_title('Price sensitivity ($)', fontsize=12)
for i in range(5):
    for j in range(5):
        val = sensitivity[i, j]
        if not np.isnan(val):
            ax2.text(j, i, f'${val:.0f}', ha='center', va='center',
                     fontsize=8, color='black', fontweight='bold')
plt.colorbar(im, ax=ax2, format='$%.0f')
plt.tight_layout()
plt.savefig(f'{ticker_name}_dcf.png', dpi=150, bbox_inches='tight')
plt.show()
print(f"Chart saved as {ticker_name}_dcf.png")

